# -*- coding: utf-8 -*-
"""Context_varification_by_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17q2uIYfwhVCGQdXEXsfwkZXSKwAjqGx4

# Tweet Context Comparison — Original vs Paraphrased
Compares 250 rows of tweet conversations using Groq API (Llama).
Output columns: `intact` (Yes/No), `original_context`, `paraphrased_context`

## 1. Install dependencies
"""

# ── CELL 1: Install dependencies ──────────────────────────────────────────
!pip install google-genai openpyxl pandas -q
print('✅ Dependencies installed.')

"""## 2. Imports & config"""

# ── CELL 2: Load API key from Colab Secrets ───────────────────────────────
from google.colab import userdata
import google.genai as genai

api_key = userdata.get('Google_API_Key')
client  = genai.Client(api_key=api_key)
print('✅ Gemini API key loaded from Colab Secrets.')

"""## 3. Load data"""

# ── CELL 3: Upload file ────────────────────────────────────────────────────
import pandas as pd
from google.colab import files

print("📂 Upload your file:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_excel(filename)  # change to pd.read_csv(filename) if CSV
print(f"✅ Loaded '{filename}' — {len(df)} rows")
print(f"   Columns: {df.columns.tolist()}")
df.head(2)

# Update the filename below to match what you uploaded
UPLOADED_FILENAME = "Lamp7_profile_Paraphrased.xlsx"  # <-- change if needed

if UPLOADED_FILENAME.endswith(".xlsx"):
    df = pd.read_excel(UPLOADED_FILENAME)
else:
    df = pd.read_csv(UPLOADED_FILENAME)

# Rename column if needed (adjust to your actual column name)
if 'profile_tweets_combined' in df.columns:
    df = df.rename(columns={'profile_tweets_combined': 'original'})

assert 'original' in df.columns and 'paraphrased' in df.columns, \
    "DataFrame must have columns named 'original' and 'paraphrased'"

print(f"Loaded {len(df)} rows")
df.head(3)

"""## 4. Prompt builder & response parser"""

SYSTEM_PROMPT = """You are an expert at analyzing conversation context and semantic fidelity.
You always respond in this exact format, nothing else:

INTACT: <Yes or No>
ORIGINAL_CONTEXT: <one sentence describing the core context of the original>
PARAPHRASED_CONTEXT: <one sentence describing the core context of the paraphrased version>"""


def build_prompt(original: str, paraphrased: str) -> str:
    return f"""Compare these two tweet conversations and evaluate if the paraphrased version preserves the core context of the original.

ORIGINAL:
\"\"\"
{original}
\"\"\"

PARAPHRASED:
\"\"\"
{paraphrased}
\"\"\"

Respond in this exact format:
INTACT: <Yes or No>
ORIGINAL_CONTEXT: <one sentence describing what the original conversation is about>
PARAPHRASED_CONTEXT: <one sentence describing what the paraphrased conversation is about>"""


def parse_response(text: str) -> dict:
    """Parse flat text response into a dict."""
    result = {"intact": None, "original_context": None, "paraphrased_context": None}
    for line in text.strip().splitlines():
        if line.startswith("INTACT:"):
            result["intact"] = line.replace("INTACT:", "").strip()
        elif line.startswith("ORIGINAL_CONTEXT:"):
            result["original_context"] = line.replace("ORIGINAL_CONTEXT:", "").strip()
        elif line.startswith("PARAPHRASED_CONTEXT:"):
            result["paraphrased_context"] = line.replace("PARAPHRASED_CONTEXT:", "").strip()
    return result

"""## 5. API call function with retry"""

import time
from google import genai
from google.colab import userdata

# --- Gemini config ---
GEMINI_API_KEY = userdata.get("Google_API_Key")
MODEL = "gemini-2.0-flash"   # or "gemini-1.5-flash", "gemini-1.5-pro"
MAX_RETRIES = 3
RETRY_DELAY = 5

gemini_client = genai.Client(api_key=GEMINI_API_KEY)


def call_llama(original: str, paraphrased: str) -> dict:
    """Call Gemini API and return parsed result."""
    prompt = build_prompt(original, paraphrased)

    for attempt in range(MAX_RETRIES):
        try:
            response = gemini_client.models.generate_content(
                model=MODEL,
                contents=SYSTEM_PROMPT + "\n\n" + prompt
            )
            raw = response.text.strip()
            return parse_response(raw)

        except Exception as e:
            print(f"  API error on attempt {attempt+1}: {e}")
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY)

    return {
        "intact": "Error",
        "original_context": None,
        "paraphrased_context": None
    }

"""## 6. Run comparison on all rows

> **Note:** Groq has rate limits (requests per minute). If you hit a `RateLimitError`, increase `RETRY_DELAY` above or add `time.sleep(1)` inside the loop below.
"""

from tqdm.notebook import tqdm
import time

results = []

# Process only the first 250 rows
for i, row in tqdm(df.head(250).iterrows(), total=250, desc="Comparing"):
    result = call_llama(
        original=str(row['original']),
        paraphrased=str(row['paraphrased'])
    )
    results.append(result)
    time.sleep(0.5)  # gentle rate-limit buffer for Groq free tier

print(f"\nDone. Processed {len(results)} rows.")

"""## 7. Build final dataframe"""

results_df = pd.DataFrame(results)

final_df = pd.concat([df.head(250).reset_index(drop=True), results_df], axis=1)

final_df.head(5)

"""## 8. Save to Excel"""

OUTPUT_FILE = 'tweet_context_comparison_results.xlsx'
final_df.to_excel(OUTPUT_FILE, index=False)
print(f"Results saved to: {OUTPUT_FILE}")

from google.colab import files
files.download(OUTPUT_FILE)

"""## 9. Summary"""

total      = len(final_df)
intact     = (final_df['intact'].str.lower() == 'yes').sum()
not_intact = (final_df['intact'].str.lower() == 'no').sum()
errors     = (final_df['intact'] == 'Error').sum()

print(f"Total rows   : {total}")
print(f"Intact (Yes) : {intact}  ({intact/total*100:.1f}%)")
print(f"Not intact   : {not_intact}  ({not_intact/total*100:.1f}%)")
print(f"Errors       : {errors}")

"""## 10. View rows where context is NOT intact"""

not_intact_df = final_df[final_df['intact'].str.lower() == 'no']
print(f"Rows not intact: {len(not_intact_df)}")
not_intact_df[['original', 'paraphrased', 'original_context', 'paraphrased_context']]