# -*- coding: utf-8 -*-
"""Evaluation_By_Gemini_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3F_VBQOV05BabgzglIfITqI0rwbbJG3
"""

# ── CELL 1: Install dependencies ──────────────────────────────────────────
!pip install google-genai openpyxl pandas -q
print('✅ Dependencies installed.')

# ── CELL 2: Load API key from Colab Secrets ───────────────────────────────
from google.colab import userdata
import google.genai as genai

api_key = userdata.get('Google_API_Key')
client  = genai.Client(api_key=api_key)
print('✅ Gemini API key loaded from Colab Secrets.')

# ── CELL 3: Upload file ────────────────────────────────────────────────────
import pandas as pd
from google.colab import files

print("📂 Upload your file:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_excel(filename)  # change to pd.read_csv(filename) if CSV
print(f"✅ Loaded '{filename}' — {len(df)} rows")
print(f"   Columns: {df.columns.tolist()}")
df.head(2)

# ── CELL 4: Run evaluation ─────────────────────────────────────────────────
import json, time
from pathlib import Path
from IPython.display import clear_output
from google.colab import files

# 👇 Update these to match your actual column names
ID_COL          = df.columns[0]   # Row ID
GENERATED_COL   = df.columns[3]   # Model-generated paraphrase
GROUNDTRUTH_COL = df.columns[2]   # Ground truth paraphrase
PROFILE_COL     = df.columns[4]   # Full original unmasked profile

print(f"ID column                   : '{ID_COL}'")
print(f"Generated paraphrase column : '{GENERATED_COL}'")
print(f"Ground truth column         : '{GROUNDTRUTH_COL}'")
print(f"Profile column              : '{PROFILE_COL}'")

# ── Limit to first 250 rows ────────────────────────────────────────────────
EVAL_LIMIT = 250
df_eval = df.head(EVAL_LIMIT).copy()
print(f"\n⚡ Evaluating first {EVAL_LIMIT} rows (out of {len(df)} total)")

ids         = df_eval[ID_COL].astype(str).tolist()
generated   = df_eval[GENERATED_COL].fillna('').astype(str).tolist()
groundtruth = df_eval[GROUNDTRUTH_COL].fillna('').astype(str).tolist()
profiles    = df_eval[PROFILE_COL].fillna('').astype(str).tolist()


# ── Config ─────────────────────────────────────────────────────────────────
MODEL         = "gemini-2.5-flash"
PROGRESS_FILE = "evaluation_progress.json"
OUTPUT_FILE   = "Evaluation_Output.xlsx"
DELAY         = 0.4
MAX_RETRIES   = 3

# ── Resume support ─────────────────────────────────────────────────────────
if Path(PROGRESS_FILE).exists():
    with open(PROGRESS_FILE) as f:
        results = json.load(f)
    print(f"↩️  Resuming — {len(results)} rows already done.")
else:
    results = {}

# ── Parse selection from response ───────────────────────────────
def parse_selection(text: str) -> str:
    """Extract Para→model or GT from response."""
    t = text.upper()
    if re.search(r'\bPARA\b', t):
        return 'model'
    if re.search(r'\bGT\b', t):
        return 'GT'
    if 'GENERATED' in t and 'MORE PERSONAL' in t:
        return 'model'
    if 'GROUND TRUTH' in t and 'MORE PERSONAL' in t:
        return 'GT'
    return 'UNCLEAR'

# ── Evaluation function ────────────────────────────────────────────────────
def evaluate(gen: str, gt: str, profile: str) -> str:
    prompt = (
        "1. [Generated paraphrase from model]\n"
        f"{gen}\n\n"
        "2. [Ground truth paraphrase]\n"
        f"{gt}\n\n"
        "Which one do you think is more personalised for the following "
        "profile? Give me your selection as (Para/GT) and justification in short in another column.\n\n"
        f"{profile}"
    )
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.models.generate_content(
                model=MODEL,
                contents=prompt
            )
            return response.text.strip()
        except Exception as e:
            if attempt < MAX_RETRIES:
                time.sleep(2 ** attempt)
            else:
                return f"ERROR: {e}"

# ── Main loop ──────────────────────────────────────────────────────────────
total      = len(generated)
errors     = 0
skipped    = 0
start_time = time.time()

for i, (gen, gt, profile) in enumerate(zip(generated, groundtruth, profiles)):
    key = str(i)
    if key in results:
        continue

    if not gen.strip():
        results[key] = 'SKIPPED: no generated paraphrase'
        skipped += 1
        continue

    out = evaluate(gen, gt, profile)
    results[key] = out

    if out.startswith('ERROR:'):
        errors += 1

    done    = len(results)
    elapsed = time.time() - start_time
    rate    = (done - skipped) / elapsed if elapsed > 0 else 0.001
    eta_min = (total - done) / rate / 60 if rate > 0 else 0
    pct     = done / total * 100
    bar     = '█' * int(pct / 2) + '░' * (50 - int(pct / 2))

    if done % 25 == 0:
        with open(PROGRESS_FILE, 'w') as f:
            json.dump(results, f)

    if done % 5 == 0 or done == total:
        clear_output(wait=True)
        print('📊 Personalisation Evaluator ')
        print(f'[{bar}] {pct:.1f}%')
        print(f'  Rows done : {done} / {total}')
        print(f'  Evaluated : {done - skipped - errors}')
        print(f'  Skipped   : {skipped}')
        print(f'  Errors    : {errors}')
        print(f'  Speed     : {rate:.2f} rows/sec')
        print(f'  ETA       : {eta_min:.1f} minutes')
        print(f"  Last row  : #{i+1} — {'⏭ skipped' if not gen.strip() else ('✓' if not out.startswith('ERROR') else '✗')}")

    time.sleep(DELAY)

# ── Save progress ──────────────────────────────────────────────────────────
with open(PROGRESS_FILE, 'w') as f:
    json.dump(results, f)

# ── Fix: Import re module and redefine parse_selection ─────────────────────
import re

def parse_selection(text: str) -> str:
    """Extract Para→model or GT from response."""
    t = text.upper()
    if re.search(r'\bPARA\b', t):
        return 'model'
    if re.search(r'\bGT\b', t):
        return 'GT'
    if 'GENERATED' in t and 'MORE PERSONAL' in t:
        return 'model'
    if 'GROUND TRUTH' in t and 'MORE PERSONAL' in t:
        return 'GT'
    return 'UNCLEAR'

# ── Build final output DataFrame with exact column order ───────────────────
evaluations = [results.get(str(i), '') for i in range(total)]
selections = [
    parse_selection(r) if not r.startswith(('SKIPPED', 'ERROR')) else r
    for r in evaluations
]

out_df = pd.DataFrame({
    'id'                      : df_eval[ID_COL].values,
    'paraphrased'             : df_eval[GENERATED_COL].values,
    'ground_truth'            : df_eval[GROUNDTRUTH_COL].values,
    'profile_tweets_combined' : df_eval[PROFILE_COL].values,
    'evaluation'              : evaluations,
    'Selection'               : selections,
})

out_df.to_excel(OUTPUT_FILE, index=False)

clear_output(wait=True)
print('✅ All done!')
print(f'   Total evaluated : {total}')
print(f'   Evaluated       : {total - skipped - errors}')
print(f'   Skipped         : {skipped}')
print(f'   Errors          : {errors}')
print(f'   Output          : {OUTPUT_FILE}')
print()
print('Selection value counts:')
print(out_df['Selection'].value_counts().to_string())

files.download(OUTPUT_FILE)
