# -*- coding: utf-8 -*-
"""flag_detection_claude (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i88cNq1CaVpKqctEcZrRzIdtaIXvQKy3

# Flag Detection · Claude API · 250 Profiles → Excel
Detects f1–f5 privacy flags in converted profiles using Claude Sonnet.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install anthropic openpyxl pandas --quiet

import os, io, re, json, time, logging
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule
import anthropic
from google.colab import userdata, files
from tqdm.notebook import tqdm

logging.basicConfig(level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger(__name__)
print("✓ Ready")

"""## Configuration
> **Before running:** open the 🔑 Secrets panel (left sidebar) and add `ANTHROPIC_API_KEY`

"""

ANTHROPIC_API_KEY = userdata.get("ANTHROPIC_API_KEY")
MODEL        = "claude-sonnet-4-5"
MAX_TOKENS   = 512
TEMPERATURE  = 0.0
RATE_DELAY   = 1.0
RETRIES      = 3
OUTPUT       = "flag_detection_results.xlsx"

WEIGHTS   = {"f1": 1, "f2": 2, "f3": 4, "f4": 3, "f5": 5}
MAX_W     = sum(WEIGHTS.values())   # 15

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
print(f"✓ Client ready  |  model={MODEL}")

"""## Upload Excel (id | Original | Converted)"""

print("Select your Excel file ↓")
uploaded = files.upload()
fname    = next(iter(uploaded))
df       = pd.read_excel(io.BytesIO(uploaded[fname]), dtype=str).fillna("")

# Auto-detect columns
COL_ID = COL_ORIG = COL_CONV = None
for col in df.columns:
    k = col.strip().lower().replace(" ","_")
    if k in ("id","user_id"):                    COL_ID   = col
    elif "original" in k or k == "profile":       COL_ORIG = col
    elif "convert" in k or "anon" in k or k == "paraphrased_profile":           COL_CONV = col

for name, c in [("id",COL_ID),("original",COL_ORIG),("converted",COL_CONV)]:
    assert c, f"Cannot find '{name}' column. Found: {list(df.columns)}"

print(f"\n✓ {len(df):,} profiles loaded from '{fname}'")
print(f"  id → '{COL_ID}' | original → '{COL_ORIG}' | converted → '{COL_CONV}'")
df[[COL_ID, COL_CONV]].head(3)

df[[COL_ID,COL_ORIG, COL_CONV]].head(3)

"""## Prompt"""

SYSTEM = """\
You are a privacy auditor. Evaluate the user profile against five rules.
Return ONLY a JSON object — no markdown, no preamble, no explanation.

Rules:
  f1 (Age & demographic identifiers):
     Does the text reveal age, generation, life-stage, or demographic markers?
     e.g. "I am 15", "as a student", generational language, school references.

  f2 (Cultural & media references):
     Does it name or strongly imply specific celebrities, TV shows, films,
     musicians, sports teams, or other identifiable cultural entities?
     e.g. Miley Cyrus, Lakers, Twilight, Taylor Swift, specific song titles.

  f3 (Personal life details):
     Does it expose family structure, relationships, location, occupation,
     health, daily routines, religion, or political affiliation?
     e.g. "my dad", "I work as", "12am here", "shopping this weekend".

  f4 (Niche & proprietary references):
     Does it contain industry jargon, brand names, niche community vocabulary,
     or product preferences that narrow the user's identity?
     e.g. specific software tools, niche hobby terms, proprietary platforms.

  f5 (Stylistic fingerprints):
     Does the writing style, vocabulary, sentence structure, punctuation, or
     tonal signature form a distinctive individual voice?
     e.g. repeated "aww", "haha lol", all-caps emphasis, verbatim stock phrases.

Output 1 if violation found, 0 if not. Add a reason ≤10 words for raised flags.

Return ONLY this JSON:
{
  "f1": 0,  "f1_reason": "",
  "f2": 0,  "f2_reason": "",
  "f3": 0,  "f3_reason": "",
  "f4": 0,  "f4_reason": "",
  "f5": 0,  "f5_reason": ""
}
"""

print("✓ Prompt defined")

"""## Parser, Scorer & Detection Function"""

EMPTY = {k:v for k,v in [("f1",0),("f1_reason",""),("f2",0),("f2_reason",""),
         ("f3",0),("f3_reason",""),("f4",0),("f4_reason",""),("f5",0),("f5_reason","")]}

def parse(raw: str) -> dict:
    result = dict(EMPTY)
    try:
        text = re.sub(r"^```(?:json)?\s*","",raw.strip(),flags=re.IGNORECASE)
        text = re.sub(r"\s*```$","",text).strip()
        m    = re.search(r"\{.*\}", text, re.DOTALL)
        obj  = json.loads(m.group(0) if m else text)
        for k in ("f1","f2","f3","f4","f5"):
            result[k]             = int(bool(obj.get(k,0)))
            result[f"{k}_reason"] = str(obj.get(f"{k}_reason","")).strip()
    except Exception:
        for k in ("f1","f2","f3","f4","f5"):
            m = re.search(rf'"{k}"\s*:\s*([01])', raw)
            if m: result[k] = int(m.group(1))
            r = re.search(rf'"{k}_reason"\s*:\s*"([^"]*)"', raw)
            if r: result[f"{k}_reason"] = r.group(1).strip()
    return result

def weighted_score(flags: dict) -> float:
    return round(sum(WEIGHTS[k]*flags[k] for k in WEIGHTS) / MAX_W, 4)

def get_verdict(flags: dict) -> str:
    return "compliant" if all(flags[k]==0 for k in WEIGHTS) else "vulnerable"

def detect(converted: str) -> dict:
    for attempt in range(1, RETRIES+1):
        try:
            resp  = client.messages.create(
                model=MODEL, max_tokens=MAX_TOKENS,
                system=SYSTEM,
                messages=[{"role":"user","content": converted.strip()}],
            )
            raw   = resp.content[0].text
            flags = parse(raw)
            return {**flags,
                    "weighted_score": weighted_score(flags),
                    "n_flags":        sum(flags[k] for k in WEIGHTS),
                    "verdict":        get_verdict(flags),
                    "raw_response":   raw}
        except Exception as e:
            log.warning("Attempt %d/%d — %s", attempt, RETRIES, e)
            if attempt < RETRIES: time.sleep(RATE_DELAY * attempt)
    return {**EMPTY, "weighted_score":None, "n_flags":None,
            "verdict":"error", "raw_response":"API error"}

print("✓ detect() defined")

"""## Run Detection on All 250 Profiles"""

results = []
total   = len(df)
pbar    = tqdm(total=total, desc="Detecting flags", unit="profile")

for i, row in df.iterrows():
    uid    = row[COL_ID]
    conv   = row[COL_CONV]
    res    = detect(conv)
    res[COL_ID] = uid
    results.append(res)

    icon = "✅" if res["verdict"]=="compliant" else "⚠️" if res["verdict"]=="vulnerable" else "❌"
    pbar.write(
        f"{icon} [{i+1:>3}/{total}] id={str(uid):<12} "
        f"score={str(res['weighted_score']):<6} "
        f"[f1={res.get('f1','?')} f2={res.get('f2','?')} "
        f"f3={res.get('f3','?')} f4={res.get('f4','?')} f5={res.get('f5','?')}] "
        f"{res['verdict']}"
    )
    pbar.update(1)
    if i+1 < total: time.sleep(RATE_DELAY)

pbar.close()
res_df = pd.DataFrame(results)

c = (res_df["verdict"]=="compliant").sum()
v = (res_df["verdict"]=="vulnerable").sum()
e = (res_df["verdict"]=="error").sum()
avg = res_df["weighted_score"].dropna().mean()
print(f"\n{'='*50}")
print(f"✓ Done — {total} profiles")
print(f"  ✅ Compliant  : {c} ({c/total*100:.1f}%)")
print(f"  ⚠️  Vulnerable : {v} ({v/total*100:.1f}%)")
print(f"  ❌ Errors     : {e}")
print(f"  Avg score    : {avg:.4f}")
print(f"{'='*50}")

"""## Export to Excel"""

wb   = Workbook()
THIN = Side(style="thin", color="CCCCCC")
BDR  = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
BF   = Font(name="Arial", size=10)
CF   = COMPLY_F = PatternFill("solid", start_color="E2EFDA")
VF   = VULN_F   = PatternFill("solid", start_color="FCE4D6")
RF   = FLAG_F   = PatternFill("solid", start_color="E24B4A")
SECT = PatternFill("solid", start_color="D6E4F0")

def write_header(ws, headers, fill_hex):
    ws.append(headers)
    for cell in ws[1]:
        cell.font      = Font(bold=True, color="FFFFFF", name="Arial", size=10)
        cell.fill      = PatternFill("solid", start_color=fill_hex)
        cell.border    = BDR
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    ws.row_dimensions[1].height = 32

# ── Sheet 1: Results ──────────────────────────────────────────────────────
ws1 = wb.active
ws1.title = "Results"
write_header(ws1,
    [COL_ID,
     "f1\n(Age/Demo)","f2\n(Cultural)","f3\n(Personal)","f4\n(Niche)","f5\n(Style)",
     "n_flags","weighted_score","verdict",
     "f1 reason","f2 reason","f3 reason","f4 reason","f5 reason"],
    "1F4E79")

for _, r in res_df.iterrows():
    ws1.append([
        r[COL_ID],
        r.get("f1",0), r.get("f2",0), r.get("f3",0), r.get("f4",0), r.get("f5",0),
        r.get("n_flags",""), r.get("weighted_score",""), r.get("verdict",""),
        r.get("f1_reason",""), r.get("f2_reason",""),
        r.get("f3_reason",""), r.get("f4_reason",""), r.get("f5_reason",""),
    ])
    rn  = ws1.max_row
    vrd = str(r.get("verdict",""))
    rf  = CF if vrd=="compliant" else VF if vrd=="vulnerable" else None
    for ci, cell in enumerate(ws1[rn], 1):
        cell.font = BF; cell.border = BDR
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        if rf: cell.fill = rf
        if ci in (2,3,4,5,6) and cell.value == 1:   # raised flag → red
            cell.fill = RF
            cell.font = Font(bold=True, color="FFFFFF", name="Arial", size=10)
    ws1.row_dimensions[rn].height = 18

# Column widths
for ci, w in enumerate([14,8,8,8,8,8,9,15,12,32,32,32,32,32], 1):
    ws1.column_dimensions[get_column_letter(ci)].width = w

# Green→yellow→red colour scale on weighted_score (col H)
last = ws1.max_row
ws1.conditional_formatting.add(f"H2:H{last}", ColorScaleRule(
    start_type="min",  start_color="63BE7B",
    mid_type="percentile", mid_value=50, mid_color="FFEB84",
    end_type="max",    end_color="F8696B"))
ws1.freeze_panes = "B2"

# ── Sheet 2: Summary ──────────────────────────────────────────────────────
ws2 = wb.create_sheet("Summary")
ws2.column_dimensions["A"].width = 44
ws2.column_dimensions["B"].width = 20

ws2.append(["FLAG DETECTION SUMMARY",""])
for c in ("A1","B1"):
    ws2[c].font = Font(bold=True, color="FFFFFF", name="Arial", size=12)
    ws2[c].fill = PatternFill("solid", start_color="1F4E79")
ws2.row_dimensions[1].height = 24

def srow(ws, label, val, bold=False, fill=None):
    ws.append([label, val])
    r = ws.max_row
    for ci in (1,2):
        cell = ws.cell(r,ci)
        cell.font   = Font(bold=bold, name="Arial", size=10)
        cell.border = BDR
        cell.alignment = Alignment(horizontal="left" if ci==1 else "center", vertical="center")
        if fill: cell.fill = fill

n      = len(res_df)
comp   = int((res_df["verdict"]=="compliant").sum())
vuln   = int((res_df["verdict"]=="vulnerable").sum())
err    = int((res_df["verdict"]=="error").sum())
scores = res_df["weighted_score"].dropna()

srow(ws2,"Total profiles",     n,    bold=True)
srow(ws2,"✅ Compliant",        comp, bold=True, fill=CF)
srow(ws2,"⚠️  Vulnerable",      vuln, bold=True, fill=VF)
srow(ws2,"❌ Errors",           err)
srow(ws2,"Avg weighted score",  round(float(scores.mean()),4) if len(scores) else "N/A")
srow(ws2,"Max possible score",  1.0)

ws2.append([])
ws2.append(["FLAG VIOLATION RATES","Count  (rate %)"])
for c in ws2[ws2.max_row]:
    c.font=Font(bold=True,name="Arial",size=10); c.fill=SECT; c.border=BDR

FLAG_INFO = [
    ("f1","Age & demographic identifiers"),
    ("f2","Cultural & media references"),
    ("f3","Personal life details"),
    ("f4","Niche & proprietary references"),
    ("f5","Stylistic fingerprints"),
]
for fk, flabel in FLAG_INFO:
    col  = res_df[fk].dropna().astype(int)
    cnt  = int(col.sum())
    rate = col.mean()*100 if len(col) else 0
    srow(ws2, f"[{fk}] {flabel}", f"{cnt}  ({rate:.1f}%)")

ws2.append([])
ws2.append(["WEIGHT TABLE","Weight"])
for c in ws2[ws2.max_row]:
    c.font=Font(bold=True,name="Arial",size=10); c.fill=SECT; c.border=BDR
for fk, flabel in sorted(FLAG_INFO, key=lambda x: -WEIGHTS[x[0]]):
    srow(ws2, f"[{fk}] {flabel}", f"{WEIGHTS[fk]} / {MAX_W}")
srow(ws2,"Formula","Σ(wᵢ·fᵢ) / Σ(wᵢ)")

wb.save(OUTPUT)
print(f"✓ Saved → {OUTPUT}")

"""## Download"""

files.download(OUTPUT)
print("✓ Downloading →", OUTPUT)