# -*- coding: utf-8 -*-
"""ParaphraseSingleTweet_By_Claude_onConvertedProfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Xyc67Gm23Oz4mO4fs63balfP1t2k85k
"""

# ── CELL 1: Install dependencies ──────────────────────────────────────────
!pip install openai openpyxl pandas -q
print('✅ Dependencies installed.')

# ── CELL 2: Load API key from Colab Secrets ───────────────────────────────
!pip install anthropic -q
import anthropic
from google.colab import userdata

api_key = userdata.get('ANTHROPIC_API_KEY')
client  = anthropic.Anthropic(api_key=api_key)

# ── Quick sanity check ─────────────────────────────────────────────────────
try:
    test = client.messages.create(
        model='claude-sonnet-4-20250514',
        max_tokens=10,
        messages=[{'role': 'user', 'content': 'Say OK'}]
    )
    print('✅ API key works! Response:', test.content[0].text.strip())
except Exception as e:
    print(f'❌ API key test failed: {e}')

# ── CELL 3: Upload file ────────────────────────────────────────────────────
import pandas as pd
from google.colab import files

print("📂 Upload your file:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_excel(filename)  # change to pd.read_csv(filename) if CSV
print(f"✅ Loaded '{filename}' — {len(df)} rows")
print(f"   Columns: {df.columns.tolist()}")
df.head(2)

# ── CELL: Set column names then run ───────────────────────────────────────
# 👇 Update these two to match your actual column names shown above
TWEET_COL   = df.columns[1]   # single-sentence tweet to paraphrase
PROFILE_COL = df.columns[3]   # full conversation history

print(f"Tweet column   : '{TWEET_COL}'")
print(f"Profile column : '{PROFILE_COL}'")

# ── Limit to first 250 rows ────────────────────────────────────────────────
EVAL_LIMIT = 250
df_eval  = df.head(EVAL_LIMIT).copy()
tweets   = df_eval[TWEET_COL].fillna('').tolist()
profiles = df_eval[PROFILE_COL].fillna('').tolist()
print(f"⚡ Evaluating first {EVAL_LIMIT} rows (out of {len(df)} total)")

# ── Config ─────────────────────────────────────────────────────────────────
PROGRESS_FILE = 'paraphrase_progress.json'
OUTPUT_FILE   = 'Paraphrased_Output.xlsx'
DELAY         = 0.4
MAX_RETRIES   = 3

from pathlib import Path
import time, json, datetime
from IPython.display import clear_output

# ── Resume support ─────────────────────────────────────────────────────────
if Path(PROGRESS_FILE).exists():
    with open(PROGRESS_FILE) as f:
        results = json.load(f)
    print(f"↩️  Resuming — {len(results)} rows already done.")
else:
    results = {}

# ── Paraphrase function ────────────────────────────────────────────────────
def paraphrase(tweet: str, profile: str) -> str:
    prompt = (
        "Paraphrase the following tweet without any explanation "
        "before or after it according to the profile:\n\n"
        f"{tweet}\n\n"
        "Profile:\n"
        f"{profile}"
    )
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            msg = client.chat.completions.create(
                model="deepseek-chat",
                max_tokens=512,
                messages=[{"role": "user", "content": prompt}]
            )
            return msg.choices[0].message.content.strip()
        except Exception as e:
            if attempt < MAX_RETRIES:
                time.sleep(2 ** attempt)
            else:
                return f"ERROR: {e}"

# ── Main loop ──────────────────────────────────────────────────────────────
total      = len(tweets)
errors     = 0
start_time = time.time()

for i, (tweet, profile) in enumerate(zip(tweets, profiles)):
    key = str(i)
    if key in results:
        continue

    out = paraphrase(tweet, profile)
    results[key] = out

    if out.startswith("ERROR:"):
        errors += 1

    done       = len(results)
    elapsed    = time.time() - start_time
    rate       = done / elapsed if elapsed > 0 else 0.001
    eta_sec    = (total - done) / rate
    eta_str    = str(datetime.timedelta(seconds=int(eta_sec)))
    runtime    = str(datetime.timedelta(seconds=int(elapsed)))
    pct        = done / total * 100
    bar        = "█" * int(pct / 2) + "░" * (50 - int(pct / 2))

    if done % 25 == 0:
        with open(PROGRESS_FILE, "w") as f:
            json.dump(results, f)

    if done % 5 == 0 or done == total:
        clear_output(wait=True)
        print("🐦 Tweet Paraphraser — Progress")
        print(f"[{bar}] {pct:.1f}%")
        print(f"  Rows done   : {done} / {total}")
        print(f"  Successful  : {done - errors}")
        print(f"  Errors      : {errors}")
        print(f"  Speed       : {rate:.2f} rows/sec")
        print(f"  Runtime     : {runtime}")
        print(f"  ETA         : {eta_str}")
        print(f"  Last row    : #{i+1} — {'✓' if not out.startswith('ERROR') else '✗'}")

    time.sleep(DELAY)

# ── Save output ────────────────────────────────────────────────────────────
with open(PROGRESS_FILE, "w") as f:
    json.dump(results, f)

total_runtime = str(datetime.timedelta(seconds=int(time.time() - start_time)))

df_eval["paraphrased"] = [results.get(str(i), "") for i in range(total)]
df_eval.to_excel(OUTPUT_FILE, index=False)

clear_output(wait=True)
print("✅ All done!")
print(f"   Rows evaluated : {total}")
print(f"   Successful     : {total - errors}")
print(f"   Errors         : {errors}")
print(f"   Total runtime  : {total_runtime}")
print(f"   Output         : {OUTPUT_FILE}")

files.download(OUTPUT_FILE)

# ── Save output ────────────────────────────────────────────────────────────
with open(PROGRESS_FILE, "w") as f:
    json.dump(results, f)

total_runtime = str(datetime.timedelta(seconds=int(time.time() - start_time)))

out_df = pd.DataFrame({
    'original_tweet' : tweets,
    'paraphrased'    : [results.get(str(i), "") for i in range(total)],
})

out_df.to_excel(OUTPUT_FILE, index=False)

clear_output(wait=True)
print("✅ All done!")
print(f"   Rows evaluated : {total}")
print(f"   Successful     : {total - errors}")
print(f"   Errors         : {errors}")
print(f"   Total runtime  : {total_runtime}")
print(f"   Output         : {OUTPUT_FILE}")

files.download(OUTPUT_FILE)